Do not expose collections
SecureCodeWarrior/public-cookbooks pull request #19
Opened 2021-01-11 21:21 UTC by rloihl-scw

exposing internal, private collections can create interesting bugs in multi-threaded environments and violates OOP encapsulation - wrapping the internal collection in an immutable class helps prevent issues and is cheaper than doing a deep copy

Co-authored-by: Mariana Mourão mmourao@securecodewarrior.com

2021-01-13 13:20 UTC, Matth-- requested changes

2021-01-13 13:20 UTC, Matth-- commented on recipes/javagotchas/descriptions/DonotexposeinternalCollection.html
> +<h2 id="recipedetails">Recipe Details</h2>
Recipe details do not belong inside the description html file

2021-01-13 13:20 UTC, Matth-- commented on recipes/javagotchas/descriptions/DonotexposeinternalCollection.html
> +<ul>
This should not be a list as there is only one list item

2021-01-13 13:20 UTC, Matth-- commented on recipes/javagotchas/descriptions/DonotexposeinternalCollection.html
> +<pre><code>availableFixes:
see previous comment

2021-01-13 13:20 UTC, Matth-- commented on recipes/javagotchas/descriptions/DonotexposeinternalCollection.html
> +<pre><code>public class ListExample {
<code> tags are obsolete

2021-01-13 13:20 UTC, Matth-- commented on recipes/javagotchas/rules.sensei
> +        "disableRuleIDs": [
We don't want disabled rule ID's on our public cookbooks (probably a copied recipe?)

2021-01-13 19:12 UTC, rloihl-scw commented on recipes/javagotchas/descriptions/DonotexposeinternalCollection.html
> +<h2 id="recipedetails">Recipe Details</h2>
removed from the markdown file as well

2021-01-13 19:59 UTC, rloihl-scw commented on recipes/javagotchas/descriptions/DonotexposeinternalCollection.html
> +<ul>
fixed

2021-01-13 20:00 UTC, rloihl-scw commented on recipes/javagotchas/descriptions/DonotexposeinternalCollection.html
> +<pre><code>public class ListExample {
reformatted the file to match this confluence page https://securecodewarrior.atlassian.net/wiki/spaces/CP/pages/1492910159/Recipe+creation+guidelines+-+January+2021

2021-01-13 20:00 UTC, rloihl-scw commented on recipes/javagotchas/rules.sensei
> +        "disableRuleIDs": [
removed

2021-01-14 15:40 UTC, downeyrobersscheuten commented on recipes/javagotchas/descriptions/DonotexposeinternalCollection.html
> +<h4>Abstract</h4>
```suggestion
<h2>Abstract</h2>
```

2021-01-14 15:40 UTC, downeyrobersscheuten commented on recipes/javagotchas/descriptions/DonotexposeinternalCollection.html
> +<h4>Description</h4>
```suggestion
<h2>Description</h2>
```

2021-01-14 15:42 UTC, downeyrobersscheuten commented on recipes/javagotchas/descriptions/DonotexposeinternalCollection.html
> +<h4>Resources</h4>
```suggestion
<h2>Resources</h2>
```

Please add some resources if they're relevant otherwise delete the resource tag

2021-01-14 18:33 UTC, merged