Sen 1846 close client
SecureCodeWarrior/public-cookbooks pull request #35
Opened 2021-01-21 12:45 UTC by LauraVerheyde

2021-01-25 13:33 UTC, nvhaver requested changes

2021-01-25 13:33 UTC, nvhaver commented on recipes/awssdk/rules.sensei
> +}
There are some cases that are not covered by this recipe. Such as:

- Multiple variables\fields of the same type (so the recipe might look at the wrong closes method call);
- Variables being locally scoped or not locally scoped.

**From the reviewer's perspective we are not sure that this rule is tractable with the current Sensei feature set. If this is not the case, please open tickets for the missing features.**

We suggest it might have to be split up into multiple rules, one per different case, to limit complexity and to be able to provide different quickfixes for the different cases. One of the quickfixes that might be useful is suggesting a try-with-resources like the following:

```
try (DynamoDbClient ddb = DynamoDbClient.create()) {...}
```

Below is some example code that can be used to test the recipe. 

```
import software.amazon.awssdk.services.dynamodb.DynamoDbClient;

public class MyClassDynamoDb {
    private DynamoDbClient ddbNotClosed;
    private DynamoDbClient ddbClosed;

    public void initDBs() {
        ddbNotClosed = DynamoDbClient.create(); // Should be marked by rule
        ddbClosed = DynamoDbClient.create();
    }

    public void closeDB() {
        ddbClosed.close();
    }

    public void localScopedOpenClose() {
        DynamoDbClient ddb = DynamoDbClient.create();
        //...
        ddb.close();
    }

    public void localScopedOpenNoClose() {
        DynamoDbClient ddb = DynamoDbClient.create(); // Should be marked by rule
        //...
    }

    public void doubleLocalOneClosed() {
        DynamoDbClient ddbClosed2 = DynamoDbClient.create();
        DynamoDbClient ddbOpen = DynamoDbClient.create(); // Should be marked by rule

        ddbClosed2.close();
    }
}
```

2021-01-25 13:33 UTC, nvhaver commented on recipes/awssdk/descriptions/ReleaseDynamoDbClientClose.html
> +</ul>
Please refer to the remarks on the previous description file.

2021-01-25 13:33 UTC, nvhaver commented on recipes/awssdk/readme.md
> +<li>Avoid hardcoding AWSSessionCredentials</li>
Please add the name/description of this rule instead. The name of the other rule should be added by the other PR. Pay attention when resolving merge conflicts that other rules are not overwritten here.

2021-01-26 13:59 UTC, LauraVerheyde commented
We've changed the searcher to only search for the close call inside the method, to avoid false negatives. 

In order to implement your suggestions for searchers, we'd indeed have to request changes to Sensei

2021-01-28 09:28 UTC, nvhaver approved these changes

2021-01-28 09:36 UTC, nvhaver approved these changes
Changes look good to me

2021-01-28 09:54 UTC, merged