SEN-1828 Add add_matomo_script in generate-docs.sh
SecureCodeWarrior/public-cookbooks pull request #37
Opened 2021-01-26 10:46 UTC by awildbrysen

Closes SEN-1828

I tried to add the matomo script but I'm not sure this is the correct way.

2021-02-09 14:38 UTC, downeyrobersscheuten approved these changes

2021-02-12 00:02 UTC, miere commented
Unfortunately, GitHub Flavoured Markdown doesn't support script tags.
The supported tags are whitelisted [here](https://github.com/gjtorikian/html-pipeline/blob/main/lib/html/pipeline/sanitization_filter.rb#L44-L106).

Will pair with @awildbrysen on this by his Monday morning.

2021-02-12 00:02 UTC, miere requested changes
Unfortunately, GitHub Flavoured Markdown doesn't support script tags.
The supported tags are whitelisted [here](https://github.com/gjtorikian/html-pipeline/blob/main/lib/html/pipeline/sanitization_filter.rb#L44-L106).

Will pair with @awildbrysen on this by his Monday morning.

2021-02-17 03:22 UTC, miere commented
@awildbrysen I moved the script to the expected place:
- Allow include scripts into the `<head>` of the page (see default.html)
- Created head.html with the Matomo script

2021-02-18 08:08 UTC, merged